### ISSUE TITLE
English translation please!

### ISSUE THREAD

**Issue by valenzine** [Yaeltex/KiloMux-Shield#1]
It would be great if you could translate the readme file! <3

**Comment by guidokritz** [comment]
Hi! I can create a pull request with the translated file. No sure though how to include it. Should I just add it to the same README.md file or create a new one? I don't know if there're any standards or conventions on how to include multilingual documentation for a repository. Any suggestions?
---
Hola! Puedo hacer un pull request con el archivo traducido. Pero no estoy seguro cómo incluirlo. Lo agrego directamente en el mismo README.md o creo un archivo nuevo con la traducción? No sé si hay algún estandar o convención sobre cómo se documenta un repositorio en varios idiomas... alguna idea?

**Comment by pablofullana** [comment]
I think it is a good practice to have the README.md file written in english and, in this case, a new README.es.md in spanish. Like in https://github.com/tiimgreen/github-cheat-sheet. Anyway, just an opinion.

**Comment by guidokritz** [comment]
@pablofullana suggestion sounds good to me. I made a pull request with the changes. Hope you find it helpful.

**Comment by sanotronics** [comment]
Excellent guys! Thanks for the input on this :) and thank you @guidokritz for the translation!!
